development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: 'abode.property.management1@gmail.com'
  :password: 'abode1234'
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: 'abode.property.management1@gmail.com'
  :password: 'abode1234'
  :enable_starttls_auto: true